// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/Bios-Marcel/cordless/windowman"
	tcell "github.com/gdamore/tcell/v2"
	messagebus "github.com/vardius/message-bus"
)

type FakeWindow struct {
	HandleKeyEventStub        func(*tcell.EventKey) *tcell.EventKey
	handleKeyEventMutex       sync.RWMutex
	handleKeyEventArgsForCall []struct {
		arg1 *tcell.EventKey
	}
	handleKeyEventReturns struct {
		result1 *tcell.EventKey
	}
	handleKeyEventReturnsOnCall map[int]struct {
		result1 *tcell.EventKey
	}
	OnRegisterStub        func(messagebus.MessageBus)
	onRegisterMutex       sync.RWMutex
	onRegisterArgsForCall []struct {
		arg1 messagebus.MessageBus
	}
	ShowStub        func(windowman.ApplicationControl) error
	showMutex       sync.RWMutex
	showArgsForCall []struct {
		arg1 windowman.ApplicationControl
	}
	showReturns struct {
		result1 error
	}
	showReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWindow) HandleKeyEvent(arg1 *tcell.EventKey) *tcell.EventKey {
	fake.handleKeyEventMutex.Lock()
	ret, specificReturn := fake.handleKeyEventReturnsOnCall[len(fake.handleKeyEventArgsForCall)]
	fake.handleKeyEventArgsForCall = append(fake.handleKeyEventArgsForCall, struct {
		arg1 *tcell.EventKey
	}{arg1})
	stub := fake.HandleKeyEventStub
	fakeReturns := fake.handleKeyEventReturns
	fake.recordInvocation("HandleKeyEvent", []interface{}{arg1})
	fake.handleKeyEventMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWindow) HandleKeyEventCallCount() int {
	fake.handleKeyEventMutex.RLock()
	defer fake.handleKeyEventMutex.RUnlock()
	return len(fake.handleKeyEventArgsForCall)
}

func (fake *FakeWindow) HandleKeyEventCalls(stub func(*tcell.EventKey) *tcell.EventKey) {
	fake.handleKeyEventMutex.Lock()
	defer fake.handleKeyEventMutex.Unlock()
	fake.HandleKeyEventStub = stub
}

func (fake *FakeWindow) HandleKeyEventArgsForCall(i int) *tcell.EventKey {
	fake.handleKeyEventMutex.RLock()
	defer fake.handleKeyEventMutex.RUnlock()
	argsForCall := fake.handleKeyEventArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeWindow) HandleKeyEventReturns(result1 *tcell.EventKey) {
	fake.handleKeyEventMutex.Lock()
	defer fake.handleKeyEventMutex.Unlock()
	fake.HandleKeyEventStub = nil
	fake.handleKeyEventReturns = struct {
		result1 *tcell.EventKey
	}{result1}
}

func (fake *FakeWindow) HandleKeyEventReturnsOnCall(i int, result1 *tcell.EventKey) {
	fake.handleKeyEventMutex.Lock()
	defer fake.handleKeyEventMutex.Unlock()
	fake.HandleKeyEventStub = nil
	if fake.handleKeyEventReturnsOnCall == nil {
		fake.handleKeyEventReturnsOnCall = make(map[int]struct {
			result1 *tcell.EventKey
		})
	}
	fake.handleKeyEventReturnsOnCall[i] = struct {
		result1 *tcell.EventKey
	}{result1}
}

func (fake *FakeWindow) OnRegister(arg1 messagebus.MessageBus) {
	fake.onRegisterMutex.Lock()
	fake.onRegisterArgsForCall = append(fake.onRegisterArgsForCall, struct {
		arg1 messagebus.MessageBus
	}{arg1})
	stub := fake.OnRegisterStub
	fake.recordInvocation("OnRegister", []interface{}{arg1})
	fake.onRegisterMutex.Unlock()
	if stub != nil {
		fake.OnRegisterStub(arg1)
	}
}

func (fake *FakeWindow) OnRegisterCallCount() int {
	fake.onRegisterMutex.RLock()
	defer fake.onRegisterMutex.RUnlock()
	return len(fake.onRegisterArgsForCall)
}

func (fake *FakeWindow) OnRegisterCalls(stub func(messagebus.MessageBus)) {
	fake.onRegisterMutex.Lock()
	defer fake.onRegisterMutex.Unlock()
	fake.OnRegisterStub = stub
}

func (fake *FakeWindow) OnRegisterArgsForCall(i int) messagebus.MessageBus {
	fake.onRegisterMutex.RLock()
	defer fake.onRegisterMutex.RUnlock()
	argsForCall := fake.onRegisterArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeWindow) Show(arg1 windowman.ApplicationControl) error {
	fake.showMutex.Lock()
	ret, specificReturn := fake.showReturnsOnCall[len(fake.showArgsForCall)]
	fake.showArgsForCall = append(fake.showArgsForCall, struct {
		arg1 windowman.ApplicationControl
	}{arg1})
	stub := fake.ShowStub
	fakeReturns := fake.showReturns
	fake.recordInvocation("Show", []interface{}{arg1})
	fake.showMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWindow) ShowCallCount() int {
	fake.showMutex.RLock()
	defer fake.showMutex.RUnlock()
	return len(fake.showArgsForCall)
}

func (fake *FakeWindow) ShowCalls(stub func(windowman.ApplicationControl) error) {
	fake.showMutex.Lock()
	defer fake.showMutex.Unlock()
	fake.ShowStub = stub
}

func (fake *FakeWindow) ShowArgsForCall(i int) windowman.ApplicationControl {
	fake.showMutex.RLock()
	defer fake.showMutex.RUnlock()
	argsForCall := fake.showArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeWindow) ShowReturns(result1 error) {
	fake.showMutex.Lock()
	defer fake.showMutex.Unlock()
	fake.ShowStub = nil
	fake.showReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeWindow) ShowReturnsOnCall(i int, result1 error) {
	fake.showMutex.Lock()
	defer fake.showMutex.Unlock()
	fake.ShowStub = nil
	if fake.showReturnsOnCall == nil {
		fake.showReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.showReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeWindow) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleKeyEventMutex.RLock()
	defer fake.handleKeyEventMutex.RUnlock()
	fake.onRegisterMutex.RLock()
	defer fake.onRegisterMutex.RUnlock()
	fake.showMutex.RLock()
	defer fake.showMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWindow) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ windowman.Window = new(FakeWindow)
